FROM mcr.microsoft.com/dotnet/sdk:7.0 AS builder

WORKDIR /src/
COPY . .
RUN dotnet restore 
RUN dotnet publish -c Release --nologo -o publish/linux

#Build runtime image
FROM mcr.microsoft.com/dotnet/runtime-deps:7.0

WORKDIR /app
COPY --from=builder /src/publish/linux/hello-service .
COPY appsettings.json .
EXPOSE 5000
ENTRYPOINT ["/app/hello-service"]
